-- Run this complete file once in Supabase: SQL Editor.
-- It creates the personal task data model, private screenshot bucket and RLS rules.

create extension if not exists pgcrypto;

create table if not exists public.cards (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 240),
  stage text not null default 'idea' check (stage in ('idea', 'todo', 'doing', 'done')),
  criteria text not null default '' check (char_length(criteria) <= 4000),
  result text not null default '' check (char_length(result) <= 4000),
  original_text text not null default '' check (char_length(original_text) <= 20000),
  organized_text text not null default '' check (char_length(organized_text) <= 20000),
  ai_analysis jsonb,
  ai_model text check (ai_model is null or char_length(ai_model) <= 100),
  ai_prompt_version text check (ai_prompt_version is null or char_length(ai_prompt_version) <= 100),
  ai_organized_at timestamptz,
  original_text_updated_at timestamptz,
  focus boolean not null default false,
  archived boolean not null default false,
  reference boolean not null default false,
  sort_order integer not null default 0 check (sort_order >= 0),
  completed_at timestamptz,
  previous_stage text check (previous_stage in ('idea', 'todo', 'doing')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists cards_owner_board_idx on public.cards(user_id, archived, stage, sort_order);
create index if not exists cards_owner_focus_idx on public.cards(user_id, focus) where focus and not archived;
create index if not exists cards_owner_completed_idx on public.cards(user_id, completed_at desc) where stage = 'done';

create table if not exists public.attachments (
  id uuid primary key default gen_random_uuid(),
  card_id bigint not null references public.cards(id) on delete cascade,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  object_key text not null unique,
  filename text not null check (char_length(filename) between 1 and 180),
  content_type text not null check (content_type in ('image/jpeg', 'image/png', 'image/webp')),
  size integer not null check (size > 0 and size <= 10485760),
  sort_order integer not null default 0 check (sort_order >= 0),
  created_at timestamptz not null default now()
);

create index if not exists attachments_owner_card_idx on public.attachments(user_id, card_id);

create or replace function public.touch_updated_at()
returns trigger language plpgsql security invoker set search_path = '' as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists cards_touch_updated_at on public.cards;
create trigger cards_touch_updated_at before update on public.cards
for each row execute function public.touch_updated_at();

create or replace function public.track_original_text_updated_at()
returns trigger language plpgsql security invoker set search_path = '' as $$
begin
  if tg_op = 'INSERT' and new.original_text <> '' then
    new.original_text_updated_at = coalesce(new.original_text_updated_at, now());
  elsif tg_op = 'UPDATE' and new.original_text is distinct from old.original_text then
    new.original_text_updated_at = now();
  end if;
  return new;
end;
$$;

drop trigger if exists cards_track_original_text on public.cards;
create trigger cards_track_original_text before insert or update of original_text on public.cards
for each row execute function public.track_original_text_updated_at();

create or replace function public.track_card_completion()
returns trigger language plpgsql security invoker set search_path = '' as $$
begin
  if tg_op = 'INSERT' and new.stage = 'done' then
    new.completed_at = coalesce(new.completed_at, now());
    new.previous_stage = coalesce(new.previous_stage, 'todo');
    new.focus = false;
  elsif tg_op = 'UPDATE' then
    if new.stage = 'done' and old.stage is distinct from 'done' then
      new.completed_at = now();
      new.previous_stage = old.stage;
      new.focus = false;
    elsif new.stage is distinct from 'done' and old.stage = 'done' then
      new.completed_at = null;
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists cards_track_completion on public.cards;
create trigger cards_track_completion before insert or update of stage on public.cards
for each row execute function public.track_card_completion();

-- The UI prevents a fourth focus item; this trigger enforces the same rule when
-- two devices save at almost the same time.
create or replace function public.enforce_focus_limit()
returns trigger language plpgsql security invoker set search_path = '' as $$
declare active_focus_count integer;
begin
  if new.focus and not new.archived and (tg_op = 'INSERT' or not old.focus or old.archived) then
    select count(*) into active_focus_count
    from public.cards
    where user_id = new.user_id and focus and not archived and id <> coalesce(new.id, 0);
    if active_focus_count >= 3 then
      raise exception '今日焦点最多保留 3 条';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists cards_enforce_focus_limit on public.cards;
create trigger cards_enforce_focus_limit before insert or update of focus, archived on public.cards
for each row execute function public.enforce_focus_limit();

alter table public.cards enable row level security;
alter table public.attachments enable row level security;

create policy "Cards are private to their owner" on public.cards
for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "Attachments are private to their owner" on public.attachments
for select to authenticated using (user_id = auth.uid());
create policy "Owners add attachments to their own cards" on public.attachments
for insert to authenticated with check (
  user_id = auth.uid() and exists (
    select 1 from public.cards where cards.id = card_id and cards.user_id = auth.uid()
  )
);
create policy "Owners update their own attachments" on public.attachments
for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "Owners delete their own attachments" on public.attachments
for delete to authenticated using (user_id = auth.uid());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('screenshots', 'screenshots', false, 10485760, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update set public = false, file_size_limit = 10485760,
  allowed_mime_types = array['image/jpeg', 'image/png', 'image/webp'];

create policy "Owners view their screenshots" on storage.objects
for select to authenticated using (
  bucket_id = 'screenshots' and (storage.foldername(name))[1] = (select auth.uid()::text)
);
create policy "Owners upload their screenshots" on storage.objects
for insert to authenticated with check (
  bucket_id = 'screenshots' and (storage.foldername(name))[1] = (select auth.uid()::text)
);
create policy "Owners delete their screenshots" on storage.objects
for delete to authenticated using (
  bucket_id = 'screenshots' and (storage.foldername(name))[1] = (select auth.uid()::text)
);
